<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Privacy Policy</title>

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
</head>

<body class="bg-gray-100 h-screen antialiased leading-none">
    <div class="flex flex-col">
        @if(Route::has('login'))
        <div class="absolute top-0 right-0 mt-4 mr-4">
            @auth
            <a href="{{ url('/home') }}"
                class="no-underline hover:underline text-sm font-normal text-teal-800 uppercase">{{ __('Home') }}</a>
            @else
            <a href="{{ route('login') }}"
                class="no-underline hover:underline text-sm font-normal text-teal-800 uppercase pr-6">{{ __('Login') }}</a>
            @if (Route::has('register'))
            <a href="{{ route('register') }}"
                class="no-underline hover:underline text-sm font-normal text-teal-800 uppercase">{{ __('Register') }}</a>
            @endif
            @endauth
        </div>
        @endif

        <div class="min-h-screen flex items-center justify-center">
            <div class="flex flex-col justify-around h-full max-w-2xl container text-gray-600">
                <div>
                    <h1 class="font-light tracking-wider text-5xl mb-6">
                        Class OAuth
                    </h1>
                    <ul class="list-reset">
                        <li class="inline pr-8">
                            <a href="/" class="no-underline hover:underline text-sm font-normal text-teal-800 uppercase"
                                title="Home">Home</a>
                        </li>
                    </ul>
                    <h2 class="my-8 text-2xl">Privacy Policy</h2>
                    <p class="mt-2 mb-4">Your privacy is important to us. It is Class OAuth's policy to respect your
                        privacy
                        regarding any
                        information we may collect from you across our website, <a
                            href="https://class-oauth.fictiveweb.com">https://class-oauth.fictiveweb.com</a>, and other
                        sites we own and operate.</p>
                    <p class="my-2">We only ask for personal information when we truly need it to provide a service to
                        you. We
                        collect it by fair and lawful means, with your knowledge and consent. We also let you know why
                        we’re collecting it and how it will be used.</p>
                    <p class="my-2">We only retain collected information for as long as necessary to provide you with
                        your requested
                        service. What data we store, we’ll protect within commercially acceptable means to prevent loss
                        and theft, as well as unauthorised access, disclosure, copying, use or modification.</p>
                    <p class="my-2">We don’t share any personally identifying information publicly or with
                        third-parties, except when
                        required to by law.</p>
                    <p class="my-2">Our website may link to external sites that are not operated by us. Please be aware
                        that we have
                        no control over the content and practices of these sites, and cannot accept responsibility or
                        liability for their respective privacy policies.</p>
                    <p class="my-2">You are free to refuse our request for your personal information, with the
                        understanding that we
                        may be unable to provide you with some of your desired services.</p>
                    <p class="my-2">Your continued use of our website will be regarded as acceptance of our practices
                        around privacy
                        and personal information. If you have any questions about how we handle user data and personal
                        information, feel free to contact us.</p>
                    <p class="my-2">This policy is effective as of 3 October 2019.</p>
                    <p class="my-2">Generated by <a title="Privacy Policy Template Generator"
                            href="https://getterms.io/">GetTerms.io</a></p>
                </div>
            </div>
        </div>
    </div>
</body>

</html>